
Router.route('/', function () {
  this.render('userFeed');
});
Router.route('/addNewProject',function(){
  this.render('addNewProject');
});
Router.route('/chat_template',function(){
  this.render('chat_template');
});
Router.route('/addNewUser',function(){
  this.render('addNewUser');
});
Router.route('/createUser',function(){
  this.render('createUser');
});
Router.route('/usersManagement',function(){
  this.render('usersManagement');
});
Router.route('/projsManagement',function(){
  this.render('projsManagement');
});
Router.route('/Profile',function(){
  this.render('ProfileTemplate');
});
Router.route('/leadershipboard',function(){
  this.render('leadershipboard');
});

Router.route('/projectProfile',function(){
  this.render('projectProfile');
});
Router.route('/generalManagement',function(){
  this.render('generalManagement');
});
Router.route('/login',function(){
  this.render('loginModal');
});
Router.route('/summary',function(){
  this.render('summary');
});
Router.route('/Feed',function(){
  this.render('userFeed');
});
